### PR TITLE
add mk19 rws

### PR DESCRIPTION
**Pull request by Ferrariic**
- Adds Turkish PARS III MK19 RWS to Squad Calc.
- Preliminary Image

**Example**
image

Resolves: https://github.com/sh4rkman/SquadCalc/issues/148

### CODE REVIEW

**Comment by Ferrariic** [comment]
image
Mk19rws image on skorpo

**Comment by Ferrariic** [comment]
Rgr that, will do! Allow me some time to make these changes.

**Comment by Ferrariic** [comment]
Velocity and gravity have been updated to 9.78 and 237 m/s from 9.8 and 238 m/s, to incorporate longer flight time with less gravity. I have attempted to use decimal places (ex. 237.5) though I did not notice a major difference.

**Comment by Ferrariic** [comment]
PR is not ready to push, as flight time will have to be incorporated to give correct estimate of range. Refer to: https://github.com/sh4rkman/SquadCalc/issues/163#issuecomment-2198242664

**Comment by sh4rkman** [comment]
added with https://github.com/sh4rkman/SquadCalc/pull/204

**Comment by Ferrariic** [comment]
Thank you!

**Pull request closed without merging**
